// Generated by `bin/rails automations:export`. Do not edit.
//
// Types for Pulsify automation handlers. Shape and nullability are introspected
// from the sandbox that runs your code, so they describe what `handle` actually
// receives.

export interface ListingContext {
  /** Which connected account the automation runs for. Absent on validation runs and plain samples; present on live runs and dry runs. */
  account: {
    id: string;
    name: string;
  };
  listing: {
    adGroups: Array<{
      /** Distinct ASINs advertised in the ad group. */
      asinCount: number;
      /** Decimal string rather than a number ("0.75"). parseFloat before comparing. Major units. */
      defaultBid: string | null;
      id: string | null;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number | null;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number | null;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      name: string | null;
      state: string | null;
    }>;
    ads: Array<{
      asin: string | null;
      id: string | null;
      sku: string | null;
      state: string | null;
    }>;
    asin: string;
    /** Null when the listing has no B2B offer. Major units. */
    b2bPrice: number | null;
    /** Trailing 30 days, rolled up eagerly. Always a number: zero rather than absent with no B2B sales. */
    b2bUnitsSold: number;
    /** Null while statuses is null. Do not read a null as false. */
    buyable: boolean | null;
    campaigns: Array<{
      /** Distinct ASINs advertised in the campaign, not just this listing's. */
      asinCount: number;
      /** Daily budget in major units, and a decimal string rather than a number ("50.0"). parseFloat before comparing. Major units. */
      budget: string | null;
      id: string | null;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number | null;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number | null;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      name: string | null;
      state: string | null;
      targetingType: string | null;
    }>;
    /** Upper price bound as Amazon last reported it. Null when unset. Same lifecycle as floor. Major units. */
    ceiling: number | null;
    /** Family of conditionType: new, used, collectible, refurbished or club. Null until Amazon reports it. */
    condition: string | null;
    /** Amazon's full condition token, such as used_very_good. Null until the listing item reports it. */
    conditionType: string | null;
    /** Null while statuses is null. Do not read a null as false. */
    deleted: boolean | null;
    /** Null while statuses is null. Do not read a null as false. */
    discoverable: boolean | null;
    enabled: boolean;
    /** FBA inventory and planning report data, camelCased from Amazon's hyphenated report columns. Null for MFN listings. Keys vary by report, so treat anything below it as optional. */
    fba: {
      /** Unit counts per age bucket, as decimal strings. */
      agedInventory: {
        invAge0To90Days: string;
        invAge181To270Days: string;
        invAge271To365Days: string;
        invAge365PlusDays: string;
        invAge91To180Days: string;
      };
      /** Quantities arrive as decimal strings, not numbers. parseInt before arithmetic. */
      inventory: {
        afnFulfillableQuantity: string;
        afnInboundShippedQuantity: string;
        afnResearchingQuantity: string;
        afnReservedQuantity: string;
        afnTotalQuantity: string;
        afnUnsellableQuantity: string;
        afnWarehouseQuantity: string;
      };
      /** Restock planning figures, as decimal strings. */
      planning: {
        available: string;
        estimatedExcessQuantity: string;
        sellThrough: string;
        unitsShippedT90: string;
        weeksOfCoverT90: string;
      };
    } | null;
    /** Fulfillment-centre report data. Null when no report has landed. Keys vary by report. */
    fc: {
      shelfLife: {
        unit: string;
        value: number;
      };
    } | null;
    /** Lower price bound as Amazon last reported it. Null when unset. A bound you set goes to Amazon and shows here once Amazon's next reading reflects it; until then list_listings lists it under mutations. Major units. */
    floor: number | null;
    /** Either "Amazon" (FBA) or "Merchant" (MFN). Never null. */
    fulfillmentChannel: string;
    /** Business days from order to ship (Amazon's lead_time_to_ship_max_days). Null when the SKU uses the account's default handling time. Writable on listings you fulfil yourself. A write queues only the requested handling time; it does not resend observed stock. */
    handlingTime: number | null;
    id: string;
    keywords: Array<{
      /** Decimal string rather than a number ("0.85"). parseFloat before comparing. Major units. */
      bid: string | null;
      id: string | null;
      matchType: string | null;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number | null;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number | null;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      state: string | null;
      /** The keyword expression. Named text here and expression in the Ads API. */
      text: string | null;
    }>;
    /** Recent mutations for the listing: all queued requests and the latest submission. Use status === "queued" to check for in-flight changes. */
    mutations: Array<{
      /** Whether Amazon accepted the request for processing; false when rejected. */
      accepted: boolean;
      createdAt: string;
      id: string;
      payload: unknown;
      response: unknown;
      /** "queued" (awaiting submission) or "submitted" (Amazon response recorded). */
      status: string;
      /** Amazon's submissionId for the patch that carried this mutation. */
      submissionId: string;
      /** ISO 8601 timestamp when Amazon's response was recorded. */
      submittedAt: string;
    }>;
    /** Major units (15.27). list_listings reports the same figure as 1527. Major units. */
    price: number | null;
    /** Available quantity. Null when Amazon has not reported one. Writable on listings you fulfil yourself; a write there is rejected on an FBA listing. */
    quantity: number | null;
    /** YYYY-MM-DD the listing is back in stock. Null when unset. Writable on listings you fulfil yourself. */
    restockDate: string | null;
    /** Zero when Amazon fulfils. On a listing you fulfil, null until an offer event carries your own offer; Pulsify no longer polls for it. Major units. */
    shipping: number | null;
    /** Merchant shipping template id, not its display name. Null until Amazon reports one; FBA listings have none. Writable on listings you fulfil yourself. */
    shippingGroup: string | null;
    /** One of "BUYABLE", "DISCOVERABLE", "DELETED". */
    statuses: Array<string>;
  };
  marketplace: {
    /** IANA zone for the listing's marketplace. Use it for any hour-of-day logic. */
    timeZone: string;
  };
  /** Mutation outbox array. Push mutation objects here to queue changes for Amazon selling partner or ads entities. Drained by the runtime after handle returns. */
  mutations: Record<string, unknown>[];
  store: {
    /** Removes a key immediately. */
    delete(key: string): void;
    /** Per-automation key/value store. Returns null for a missing key. Values expire after 1 day. */
    get(key: string): unknown;
    /** Persists a JSON-serializable value under a key for 1 day. */
    set(key: string, value: unknown): void;
  };
  /** One entry per enabled webhook on the account, keyed by name. Call webhooks.<name>.post(payload); a string payload is wrapped as { text: ... }. Empty when the account has none. */
  webhooks: Record<string, { post(payload: unknown): void }>;
}

export interface SellerContext {
  /** Which connected account the automation runs for. Absent on validation runs and plain samples; present on live runs and dry runs. */
  account: {
    id: string;
    name: string;
  };
  /** Mutation outbox array. Push mutation objects here to queue changes for Amazon selling partner or ads entities. Drained by the runtime after handle returns. */
  mutations: Record<string, unknown>[];
  selling_partner: {
    id: string;
    /** snake_case, as above. */
    marketplace_id: string;
    /** snake_case, unlike every other context key. Historic, and renaming it would break live automations. */
    selling_partner_id: string;
  };
  store: {
    /** Removes a key immediately. */
    delete(key: string): void;
    /** Per-automation key/value store. Returns null for a missing key. Values expire after 1 day. */
    get(key: string): unknown;
    /** Persists a JSON-serializable value under a key for 1 day. */
    set(key: string, value: unknown): void;
  };
  /** One entry per enabled webhook on the account, keyed by name. Call webhooks.<name>.post(payload); a string payload is wrapped as { text: ... }. Empty when the account has none. */
  webhooks: Record<string, { post(payload: unknown): void }>;
}

export interface CampaignContext {
  /** Which connected account the automation runs for. Absent on validation runs and plain samples; present on live runs and dry runs. */
  account: {
    id: string;
    name: string;
  };
  budget: {
    /** The budget figure carried by the firing event, not the campaign's current budget. Null outside budget-usage events. Major units. */
    amount: number;
    /** Which half of the context you were handed: "CAMPAIGN" means context.campaign is present, "PORTFOLIO" means context.portfolio is present. Null outside budget-usage events. */
    scopeType: string;
    /** ISO 8601 event time. Null outside budget-usage events. */
    updatedAt: string;
    /** Percentage of budget consumed, 0-100. Amazon emits one per 5% increment. Null outside budget-usage events. */
    usagePercentage: number;
  };
  campaign: {
    adProduct: string;
    /** Daily budget in major units. A number on budget-usage events and a decimal string on entity-change events. parseFloat handles both. Major units. */
    budget: number;
    campaignId: number;
    /** Pulsify's own id. Null when the changed campaign has not been synced yet. */
    id: string;
    name: string;
    state: string;
    targetingType: string;
  };
  hourlyConversions: Array<{
    conversions: number;
    hour: string;
    /** Major units. */
    sales: number;
    unitsOrdered: number;
  }>;
  hourlyTraffic: Array<{
    clicks: number;
    /** Major units. */
    cost: number;
    hour: string;
    impressions: number;
  }>;
  /** Mutation outbox array. Push mutation objects here to queue changes for Amazon selling partner or ads entities. Drained by the runtime after handle returns. */
  mutations: Record<string, unknown>[];
  store: {
    /** Removes a key immediately. */
    delete(key: string): void;
    /** Per-automation key/value store. Returns null for a missing key. Values expire after 1 day. */
    get(key: string): unknown;
    /** Persists a JSON-serializable value under a key for 1 day. */
    set(key: string, value: unknown): void;
  };
  /** One entry per enabled webhook on the account, keyed by name. Call webhooks.<name>.post(payload); a string payload is wrapped as { text: ... }. Empty when the account has none. */
  webhooks: Record<string, { post(payload: unknown): void }>;
}

export interface PortfolioContext {
  /** Which connected account the automation runs for. Absent on validation runs and plain samples; present on live runs and dry runs. */
  account: {
    id: string;
    name: string;
  };
  budget: {
    /** The budget figure carried by the firing event, not the campaign's current budget. Null outside budget-usage events. Major units. */
    amount: number;
    /** Which half of the context you were handed: "CAMPAIGN" means context.campaign is present, "PORTFOLIO" means context.portfolio is present. Null outside budget-usage events. */
    scopeType: string;
    /** ISO 8601 event time. Null outside budget-usage events. */
    updatedAt: string;
    /** Percentage of budget consumed, 0-100. Amazon emits one per 5% increment. Null outside budget-usage events. */
    usagePercentage: number;
  };
  /** Mutation outbox array. Push mutation objects here to queue changes for Amazon selling partner or ads entities. Drained by the runtime after handle returns. */
  mutations: Record<string, unknown>[];
  /** Present instead of context.campaign when a portfolio budget crosses an increment. Check budget.scopeType, or the presence of this object, before reading context.campaign. */
  portfolio: {
    /** The portfolio's own budget cap, not the figure from the firing event. That one is budget.amount. Null when the portfolio has no cap set. Major units. */
    budget: number;
    /** Date the budget window closes, ISO 8601. Null for an open-ended recurring budget, which is the common case, and null when the portfolio has no budget at all. */
    budgetEndDate: string | null;
    /** How Amazon renews the cap, e.g. "MONTHLY_RECURRING" or "DATE_RANGE". Null when the portfolio has no budget. */
    budgetPolicy: string;
    /** Date the budget window opens, ISO 8601 (2026-06-01). Null when the portfolio has no budget. */
    budgetStartDate: string;
    id: string;
    /** Whether Amazon still considers the portfolio within its budget. Always a boolean, never null. */
    inBudget: boolean;
    name: string;
    portfolioId: number;
    state: string;
  };
  store: {
    /** Removes a key immediately. */
    delete(key: string): void;
    /** Per-automation key/value store. Returns null for a missing key. Values expire after 1 day. */
    get(key: string): unknown;
    /** Persists a JSON-serializable value under a key for 1 day. */
    set(key: string, value: unknown): void;
  };
  /** One entry per enabled webhook on the account, keyed by name. Call webhooks.<name>.post(payload); a string payload is wrapped as { text: ... }. Empty when the account has none. */
  webhooks: Record<string, { post(payload: unknown): void }>;
}

export interface MetricsContext {
  /** Which connected account the automation runs for. Absent on validation runs and plain samples; present on live runs and dry runs. */
  account: {
    id: string;
    name: string;
  };
  budget: {
    /** The budget figure carried by the firing event, not the campaign's current budget. Null outside budget-usage events. Major units. */
    amount: number | null;
    /** Which half of the context you were handed: "CAMPAIGN" means context.campaign is present, "PORTFOLIO" means context.portfolio is present. Null outside budget-usage events. */
    scopeType: string | null;
    /** ISO 8601 event time. Null outside budget-usage events. */
    updatedAt: string | null;
    /** Percentage of budget consumed, 0-100. Amazon emits one per 5% increment. Null outside budget-usage events. */
    usagePercentage: number | null;
  };
  campaign: {
    adProduct: string;
    /** Daily budget in major units. A number on budget-usage events and a decimal string on entity-change events. parseFloat handles both. Major units. */
    budget: string;
    campaignId: number;
    /** Pulsify's own id. Null when the changed campaign has not been synced yet. */
    id: string | null;
    name: string;
    state: string;
    targetingType: string;
  };
  hourlyConversions: unknown;
  hourlyTraffic: unknown;
  /** One hour of Sponsored Products performance for one campaign. Traffic feeds carry impressions, clicks and cost; conversion feeds carry conversions, sales and unitsOrdered. Read defensively: which keys are present depends on the stream type. */
  metrics: {
    conversions: number;
    /** Which feed produced it: "sp-traffic" or "sp-conversion". */
    dataset: string;
    /** The hour this summary covers, ISO 8601. Not the time it was delivered. */
    hour: string;
    /** How many raw feed rows were rolled up into this summary. */
    records: number;
    /** Attributed sales for the hour. Conversion feeds only. Major units. */
    sales: number;
    unitsOrdered: number;
  };
  /** Mutation outbox array. Push mutation objects here to queue changes for Amazon selling partner or ads entities. Drained by the runtime after handle returns. */
  mutations: Record<string, unknown>[];
  store: {
    /** Removes a key immediately. */
    delete(key: string): void;
    /** Per-automation key/value store. Returns null for a missing key. Values expire after 1 day. */
    get(key: string): unknown;
    /** Persists a JSON-serializable value under a key for 1 day. */
    set(key: string, value: unknown): void;
  };
  /** One entry per enabled webhook on the account, keyed by name. Call webhooks.<name>.post(payload); a string payload is wrapped as { text: ... }. Empty when the account has none. */
  webhooks: Record<string, { post(payload: unknown): void }>;
}

export interface ChangeContext {
  /** Which connected account the automation runs for. Absent on validation runs and plain samples; present on live runs and dry runs. */
  account: {
    id: string;
    name: string;
  };
  budget: {
    /** The budget figure carried by the firing event, not the campaign's current budget. Null outside budget-usage events. Major units. */
    amount: number | null;
    /** Which half of the context you were handed: "CAMPAIGN" means context.campaign is present, "PORTFOLIO" means context.portfolio is present. Null outside budget-usage events. */
    scopeType: string | null;
    /** ISO 8601 event time. Null outside budget-usage events. */
    updatedAt: string | null;
    /** Percentage of budget consumed, 0-100. Amazon emits one per 5% increment. Null outside budget-usage events. */
    usagePercentage: number | null;
  };
  campaign: {
    adProduct: string;
    /** Daily budget in major units. A number on budget-usage events and a decimal string on entity-change events. parseFloat handles both. Major units. */
    budget: string;
    campaignId: number;
    /** Pulsify's own id. Null when the changed campaign has not been synced yet. */
    id: string | null;
    name: string;
    state: string;
    targetingType: string;
  };
  /** The raw entity-change payload as Amazon sent it, camelCase and unmodified. Keys differ per stream type, so read defensively. */
  change: {
    adGroupId: string;
    adId: string;
    campaignId: string;
    /** snake_case, as Amazon sends it. */
    dataset_id: string;
    lastUpdatedDateTime: string;
    notificationType: string;
    state: string;
  };
  hourlyConversions: unknown;
  hourlyTraffic: unknown;
  /** Mutation outbox array. Push mutation objects here to queue changes for Amazon selling partner or ads entities. Drained by the runtime after handle returns. */
  mutations: Record<string, unknown>[];
  store: {
    /** Removes a key immediately. */
    delete(key: string): void;
    /** Per-automation key/value store. Returns null for a missing key. Values expire after 1 day. */
    get(key: string): unknown;
    /** Persists a JSON-serializable value under a key for 1 day. */
    set(key: string, value: unknown): void;
  };
  /** One entry per enabled webhook on the account, keyed by name. Call webhooks.<name>.post(payload); a string payload is wrapped as { text: ... }. Empty when the account has none. */
  webhooks: Record<string, { post(payload: unknown): void }>;
}

export type AutomationContext =
  | ListingContext
  | SellerContext
  | CampaignContext
  | PortfolioContext
  | MetricsContext
  | ChangeContext;

/** The context interface each stream type's handler receives. */
export interface StreamTypeContexts {
  ACCOUNT_STATUS_CHANGED: SellerContext;
  AD_CHANGE: ChangeContext;
  AD_GROUP_CHANGE: ChangeContext;
  ANY_OFFER_CHANGED: ListingContext;
  B2B_ANY_OFFER_CHANGED: ListingContext;
  BRANDED_ITEM_CONTENT_CHANGE: ListingContext;
  BUDGET_USAGE: CampaignContext | PortfolioContext;
  CAMPAIGN_CHANGE: ChangeContext;
  DATA_KIOSK_QUERY_PROCESSING_FINISHED: ListingContext;
  DETAIL_PAGE_TRAFFIC_EVENT: SellerContext;
  FBA_INVENTORY_AVAILABILITY_CHANGES: ListingContext;
  FBA_OUTBOUND_SHIPMENT_STATUS: SellerContext;
  FEED_PROCESSING_FINISHED: SellerContext;
  FULFILLMENT_ORDER_STATUS: SellerContext;
  ITEM_SALES_EVENT_CHANGE: SellerContext;
  LISTINGS_ITEM_ISSUES_CHANGE: ListingContext;
  LISTINGS_ITEM_MFN_QUANTITY_CHANGE: ListingContext;
  LISTINGS_ITEM_STATUS_CHANGE: ListingContext;
  ORDER_CHANGE: ListingContext;
  PRICING_HEALTH: ListingContext;
  REPORT_PROCESSING_FINISHED: ListingContext;
  SP_CONVERSION: MetricsContext;
  SP_TRAFFIC: MetricsContext;
  TARGET_CHANGE: ChangeContext;
}

export type AutomationHandler<C extends AutomationContext = AutomationContext> = (
  event: unknown,
  context: C,
) => C;
