// Generated by `bin/rails automations:export`. Do not edit.
//
// Types for Pulsify automation handlers. Shape and nullability are introspected
// from the sandbox that runs your code, so they describe what `handle` actually
// receives.

export type AdsTargetType = "Campaign" | "AdGroup" | "Ad" | "Target";
export type MutationTargetType = "Listing" | "AdvertisingProfile" | AdsTargetType;
export interface MutationTarget<T extends MutationTargetType> { type: T; id: string }
/** Native Sponsored Products update or create object. Discover fields with get_mutation_schema. */
export type NativeAdsPayload = Record<string, unknown>;
export interface ListingPatch {
  op: "add" | "replace" | "delete" | "merge";
  path: string;
  value?: unknown[];
}
export type MutationRequest =
  | {
      target: MutationTarget<"Listing">;
      action: "update";
      payload: { productType: string; patches: ListingPatch[] };
    }
  | { target: MutationTarget<AdsTargetType>; action: "update"; payload: NativeAdsPayload }
  | { target: MutationTarget<AdsTargetType>; action: "archive"; payload: Record<string, never> }
  // A creation targets the authorized parent. The created child arrives later, on the parent's receipt.
  | { target: MutationTarget<"AdvertisingProfile">; action: "create_campaign"; payload: NativeAdsPayload }
  | {
      target: MutationTarget<"Campaign">;
      action: "create_ad_group" | "create_target";
      payload: NativeAdsPayload;
    }
  | { target: MutationTarget<"AdGroup">; action: "create_ad" | "create_target"; payload: NativeAdsPayload };

export type CreationAction = "create_campaign" | "create_ad_group" | "create_ad" | "create_target";

export interface MutationSummary {
  id: string;
  targetType: MutationTargetType;
  targetId: string;
  action: "update" | "archive" | CreationAction;
  /** Pending while queued, submitting or uncertain. Every other status is final. */
  status: "queued" | "submitting" | "submitted" | "blocked" | "uncertain" | "unresolved";
  outcome: string | null;
  accepted: boolean | null;
  payload: Record<string, unknown>;
  response: Record<string, unknown>;
  httpStatus: number | null;
  errorMessage: string | null;
  createdAt: string;
  submittedAt: string | null;
  submissionId: string | null;
  /** What a confirmed creation produced. It is itself a valid target for the next request. */
  created: (MutationTarget<AdsTargetType> & { id: string | null; providerId: string }) | null;
  /** What reconciliation established for a creation whose reply was lost. */
  reconciliation: Record<string, unknown>;
}

export interface ListingContext {
  /** Which connected account the automation runs for. Absent on validation runs and plain samples; present on live runs and dry runs. */
  account: {
    id: string;
    name: string;
  };
  /** The advertising profiles create_campaign may target: on a listing, the account's profiles in the listing's marketplace; on a campaign or portfolio, its own profile. Empty when the account has no Ads connection there. */
  advertisingProfiles: Array<{
    /** Two-letter country of the profile's marketplace. A new campaign's countries and marketplaces, when given, must name only this. */
    countryCode: string | null;
    /** Currency of every budget and bid under this profile. Native Ads money uses major units. */
    currencyCode: string | null;
    /** Pulsify's local advertising profile id. With type, it names this profile as a mutation target. */
    id: string;
    marketplaceId: string | null;
    /** Campaign creations requested on this profile: every queued, submitting and uncertain request, plus the latest settled receipt of each attempted creation. Read created for the new campaign. */
    mutations: MutationSummary[];
    /** Amazon's advertising profile id. */
    profileId: number | null;
    /** Explicit mutation target type. Use this object as the target of create_campaign. */
    type: "AdvertisingProfile";
  }>;
  listing: {
    adGroups: Array<{
      adGroupId: number | null;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string | null;
      /** Distinct ASINs advertised in the ad group. */
      asinCount: number;
      campaignLocalId: string | null;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string | null;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      /** Decimal string rather than a number ("0.75"). parseFloat before comparing. Major units. */
      defaultBid: string | null;
      id: string;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number | null;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number | null;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      name: string | null;
      /** Amazon's advertising profile id. */
      profileId: number | null;
      state: string | null;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "AdGroup";
    }>;
    ads: Array<{
      adGroupLocalId: string | null;
      adId: number | null;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string | null;
      asin: string | null;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string | null;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number | null;
      sku: string | null;
      state: string | null;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Ad";
    }>;
    asin: string;
    /** Null when the listing has no B2B offer. Major units. */
    b2bPrice: number | null;
    /** Trailing 30 days, rolled up eagerly. Always a number: zero rather than absent with no B2B sales. */
    b2bUnitsSold: number;
    blocked: boolean;
    /** Null while statuses is null. Do not read a null as false. */
    buyable: boolean | null;
    campaigns: Array<{
      adProduct: string | null;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string | null;
      /** Distinct ASINs advertised in the campaign, not just this listing's. */
      asinCount: number;
      /** Daily budget in major units, and a decimal string rather than a number ("50.0"). parseFloat before comparing. Major units. */
      budget: string | null;
      campaignId: number | null;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string | null;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number | null;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number | null;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      name: string | null;
      /** Amazon's advertising profile id. */
      profileId: number | null;
      state: string | null;
      targetingType: string | null;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Campaign";
    }>;
    /** Upper price bound as Amazon last reported it. Null when unset. Same lifecycle as floor. Major units. */
    ceiling: number | null;
    /** Family of conditionType: new, used, collectible, refurbished or club. Null until Amazon reports it. */
    condition: string | null;
    /** Amazon's full condition token, such as used_very_good. Null until the listing item reports it. */
    conditionType: string | null;
    /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
    currencyCode: string;
    /** Raw Amazon source snapshots, with original keys and units. Contents vary with the sources received; missing sources are absent. FBA report stock is under data.fba.inventory (afn-fulfillable-quantity, afn-inbound-shipped-quantity, etc.). Submitted MFN stock is under data.listings_item.attributes.fulfillment_availability; observed availability is under data.listings_item.fulfillmentAvailability. data.notifications holds the latest accepted envelope of each type, including EventTime. Notifications do not overwrite report or crawl snapshots. Choose the source and stock measure your automation needs. */
    data: Record<string, unknown>;
    /** Coupons and promotions covering this listing's ASIN whose dates include now, as of dealsReportedAt. Null until both the coupon and promotion reports have synced, so null means unknown, not none. An empty array means both synced and nothing is active. A deal that started and ended between syncs never appears. */
    deals: Array<{
      /** Amazon's report entry with its keys unchanged. A coupon carries its budget and redemption totals; a promotion carries status, type and per-ASIN sales. asins or includedProducts keeps only this listing's ASIN. Totals are cumulative through the day before the last sync. Read status yourself: dates alone do not say whether Amazon cancelled a promotion. */
      data: Record<string, unknown>;
      /** ISO 8601, UTC. A deal counts as active while startsAt <= now < endsAt, but Amazon can end one earlier (a budget runs out, or it is cancelled) before the next sync. */
      endsAt: string;
      id: string;
      kind: string;
      /** ISO 8601, UTC. When this deal's own totals in data were last refreshed from Amazon's report. A deal that started long ago in an older quarter refreshes less often than dealsReportedAt, so read this to judge how current its totals are. */
      reportedAt: string;
      startsAt: string;
    }> | null;
    /** ISO 8601 time when both reports last synced (the older of the two types' latest downloads). A deal missing from deals is missing as of this time. It does not say how current each deal's totals are: read the deal's own reportedAt. Null while deals is null. */
    dealsReportedAt: string | null;
    /** Null while statuses is null. Do not read a null as false. */
    deleted: boolean | null;
    /** Null while statuses is null. Do not read a null as false. */
    discoverable: boolean | null;
    /** FBA inventory and planning report data, camelCased from Amazon's hyphenated report columns. Null for MFN listings. Keys vary by report, so treat anything below it as optional. */
    fba: {
      /** Unit counts per age bucket, as decimal strings. */
      agedInventory: {
        invAge0To90Days: string;
        invAge181To270Days: string;
        invAge271To365Days: string;
        invAge365PlusDays: string;
        invAge91To180Days: string;
      };
      /** Quantities arrive as decimal strings, not numbers. parseInt before arithmetic. */
      inventory: {
        afnFulfillableQuantity: string;
        afnInboundShippedQuantity: string;
        afnResearchingQuantity: string;
        afnReservedQuantity: string;
        afnTotalQuantity: string;
        afnUnsellableQuantity: string;
        afnWarehouseQuantity: string;
      };
      /** Restock planning figures, as decimal strings. */
      planning: {
        available: string;
        estimatedExcessQuantity: string;
        sellThrough: string;
        unitsShippedT90: string;
        weeksOfCoverT90: string;
      };
    } | null;
    /** Fulfillment-centre report data. Null when no report has landed. Keys vary by report. */
    fc: {
      shelfLife: {
        unit: string;
        value: number;
      };
    } | null;
    /** Lower price bound as Amazon last reported it. Null when unset. A bound you set goes to Amazon and shows here once Amazon's next reading reflects it; until then list_listings lists it under mutations. Major units. */
    floor: number | null;
    /** Either "Amazon" (FBA) or "Merchant" (MFN). Never null. */
    fulfillmentChannel: string;
    /** Business days from order to ship (Amazon's lead_time_to_ship_max_days). Null when the SKU uses the account's default handling time. Writable on listings you fulfil yourself. A write queues only the requested handling time; it does not resend observed stock. */
    handlingTime: number | null;
    id: string;
    keywords: Array<{
      adGroupLocalId: string | null;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string | null;
      /** Decimal string rather than a number ("0.85"). parseFloat before comparing. Major units. */
      bid: string | null;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string | null;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      matchType: string | null;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number | null;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number | null;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number | null;
      state: string | null;
      targetId: number | null;
      /** Amazon targeting category: keyword, auto, product or product_category. */
      targetType: string;
      /** The keyword expression. Named text here and expression in the Ads API. */
      text: string | null;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Target";
    }>;
    /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
    mutations: MutationSummary[];
    /** Exclusions: negative keywords and negative product targets, at ad-group and campaign level. Kept apart from targets and keywords because nothing bids on them and Amazon reports no performance for them, so they carry no bid and no metrics30. Update and archive them like any target. */
    negativeTargets: Array<{
      /** Pulsify's local ad group id. Null for a campaign-level exclusion. */
      adGroupLocalId: string | null;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string | null;
      /** Pulsify's local campaign id. Every exclusion belongs to a campaign. */
      campaignLocalId: string | null;
      /** Currency of the advertising profile. */
      currencyCode: string | null;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      /** Amazon's targetLevel: AD_GROUP or CAMPAIGN. */
      level: string;
      matchType: string | null;
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number | null;
      state: string | null;
      targetId: number | null;
      /** Amazon targeting category: keyword, product or product_category. */
      targetType: string;
      /** The excluded keyword or product expression. Named text here and expression in the Ads API. */
      text: string | null;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Target";
    }>;
    /** Major units (15.27). list_listings reports the same figure as 1527. Major units. */
    price: number | null;
    /** Amazon product type for native listing patches. Use PRODUCT when absent. */
    productType: string | null;
    /** YYYY-MM-DD the listing is back in stock. Null when unset. Writable on listings you fulfil yourself. */
    restockDate: string | null;
    /** Zero when Amazon fulfils. On a listing you fulfil, null until an offer event carries your own offer; Pulsify no longer polls for it. Major units. */
    shipping: number | null;
    /** Merchant shipping template id, not its display name. Null until Amazon reports one; FBA listings have none. Writable on listings you fulfil yourself. */
    shippingGroup: string | null;
    /** One of "BUYABLE", "DISCOVERABLE", "DELETED". */
    statuses: Array<string>;
    /** Every positive targeting category: keywords, automatic and product targets. Exclusions are in negativeTargets. */
    targets: Array<{
      adGroupLocalId: string | null;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string | null;
      /** Decimal string rather than a number ("0.85"). parseFloat before comparing. Major units. */
      bid: string | null;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string | null;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      matchType: string | null;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number | null;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number | null;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number | null;
      state: string | null;
      targetId: number | null;
      /** Amazon targeting category: keyword, auto, product or product_category. */
      targetType: string;
      /** The keyword expression. Named text here and expression in the Ads API. */
      text: string | null;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Target";
    }>;
    /** Explicit mutation target type. Use this object as the mutation target. */
    type: "Listing";
  };
  marketplace: {
    /** The listing's marketplace, e.g. "ATVPDKIKX0DER". Matches the MarketplaceId Amazon sends on region-wide events, so use it to pick the entry for this listing rather than reading marketplace id out of raw listing data. */
    marketplaceId: string;
    /** IANA zone for the listing's marketplace. Use it for any hour-of-day logic. */
    timeZone: string;
  };
  /** Mutation outbox array, drained after handle returns. Each entry is exactly { target, action, payload }. Targets carry explicit type and local id. Use context.listing, context.campaign, or their campaigns, adGroups, ads, targets or keywords arrays. Listing update payloads contain productType and a non-empty native patches array. Ads update payloads are native Sponsored Products objects; archive uses an empty payload. A creation targets the authorized parent: create_campaign an entry of advertisingProfiles, create_ad_group a campaign, create_ad an ad group, create_target an ad group or, for an exclusion, a campaign. Its payload is Amazon's native create object; Pulsify derives adProduct and the parent ID. Nothing is returned synchronously: a later run reads the parent's mutations[].created and targets it. Listing and advertising events share this contract. Use get_mutation_schema for the native schema. At most 50 requests and 100000 serialized payload bytes per run. */
  mutations: MutationRequest[];
  store: {
    /** Removes a key immediately. */
    delete(key: string): void;
    /** Per-automation key/value store. Returns null for a missing key. Values expire after 1 day. */
    get(key: string): unknown;
    /** Persists a JSON-serializable value under a key for 1 day. */
    set(key: string, value: unknown): void;
  };
  /** One entry per enabled webhook on the account, keyed by name. Call webhooks.<name>.post(payload); a string payload is wrapped as { text: ... }. Empty when the account has none. */
  webhooks: Record<string, { post(payload: unknown): void }>;
}

export interface SellerContext {
  /** Which connected account the automation runs for. Absent on validation runs and plain samples; present on live runs and dry runs. */
  account: {
    id: string;
    name: string;
  };
  /** Mutation outbox array, drained after handle returns. Each entry is exactly { target, action, payload }. Targets carry explicit type and local id. Use context.listing, context.campaign, or their campaigns, adGroups, ads, targets or keywords arrays. Listing update payloads contain productType and a non-empty native patches array. Ads update payloads are native Sponsored Products objects; archive uses an empty payload. A creation targets the authorized parent: create_campaign an entry of advertisingProfiles, create_ad_group a campaign, create_ad an ad group, create_target an ad group or, for an exclusion, a campaign. Its payload is Amazon's native create object; Pulsify derives adProduct and the parent ID. Nothing is returned synchronously: a later run reads the parent's mutations[].created and targets it. Listing and advertising events share this contract. Use get_mutation_schema for the native schema. At most 50 requests and 100000 serialized payload bytes per run. */
  mutations: MutationRequest[];
  selling_partner: {
    id: string;
    /** snake_case, as above. */
    marketplace_id: string;
    /** snake_case, unlike every other context key. Historic, and renaming it would break live automations. */
    selling_partner_id: string;
  };
  store: {
    /** Removes a key immediately. */
    delete(key: string): void;
    /** Per-automation key/value store. Returns null for a missing key. Values expire after 1 day. */
    get(key: string): unknown;
    /** Persists a JSON-serializable value under a key for 1 day. */
    set(key: string, value: unknown): void;
  };
  /** One entry per enabled webhook on the account, keyed by name. Call webhooks.<name>.post(payload); a string payload is wrapped as { text: ... }. Empty when the account has none. */
  webhooks: Record<string, { post(payload: unknown): void }>;
}

export interface CampaignContext {
  /** Which connected account the automation runs for. Absent on validation runs and plain samples; present on live runs and dry runs. */
  account: {
    id: string;
    name: string;
  };
  /** The advertising profiles create_campaign may target: on a listing, the account's profiles in the listing's marketplace; on a campaign or portfolio, its own profile. Empty when the account has no Ads connection there. */
  advertisingProfiles: Array<{
    /** Two-letter country of the profile's marketplace. A new campaign's countries and marketplaces, when given, must name only this. */
    countryCode: string;
    /** Currency of every budget and bid under this profile. Native Ads money uses major units. */
    currencyCode: string;
    /** Pulsify's local advertising profile id. With type, it names this profile as a mutation target. */
    id: string;
    marketplaceId: string;
    /** Campaign creations requested on this profile: every queued, submitting and uncertain request, plus the latest settled receipt of each attempted creation. Read created for the new campaign. */
    mutations: MutationSummary[];
    /** Amazon's advertising profile id. */
    profileId: number;
    /** Explicit mutation target type. Use this object as the target of create_campaign. */
    type: "AdvertisingProfile";
  }>;
  budget: {
    /** The budget figure carried by the firing event, not the campaign's current budget. Null outside budget-usage events. Major units. */
    amount: number;
    /** Which half of the context you were handed: "CAMPAIGN" means context.campaign is present, "PORTFOLIO" means context.portfolio is present. Null outside budget-usage events. */
    scopeType: string;
    /** ISO 8601 event time. Null outside budget-usage events. */
    updatedAt: string;
    /** Percentage of budget consumed, 0-100. Amazon emits one per 5% increment. Null outside budget-usage events. */
    usagePercentage: number;
  };
  campaign: {
    adGroups: Array<{
      adGroupId: number;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string;
      /** Distinct ASINs advertised in the ad group. */
      asinCount: number;
      campaignLocalId: string;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      /** Decimal string rather than a number ("0.75"). parseFloat before comparing. Major units. */
      defaultBid: string;
      id: string;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      name: string;
      /** Amazon's advertising profile id. */
      profileId: number;
      state: string;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "AdGroup";
    }>;
    adProduct: string;
    ads: Array<{
      adGroupLocalId: string;
      adId: number;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string;
      asin: string;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number;
      sku: string;
      state: string;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Ad";
    }>;
    /** Pulsify's local advertising profile id. */
    advertisingProfileId: string;
    /** Distinct ASINs advertised in the campaign, not just this listing's. */
    asinCount: number;
    /** Daily budget in major units. A number on budget-usage events and a decimal string on entity-change events. parseFloat handles both. Major units. */
    budget: string;
    campaignId: number;
    /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
    currencyCode: string;
    /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
    data: Record<string, unknown>;
    /** Coupons and promotions covering any ASIN this campaign advertises, across the account's inventories in the profile's marketplace, whose dates include now, as of dealsReportedAt. Null until both reports have synced for every such inventory, so null means unknown, not none. */
    deals: Array<{
      /** Amazon's report entry with its keys unchanged, trimmed to the ASINs this campaign advertises. Read status yourself: dates alone do not say whether Amazon cancelled a promotion. */
      data: Record<string, unknown>;
      /** ISO 8601, UTC. A deal counts as active while startsAt <= now < endsAt, but Amazon can end one earlier before the next sync. */
      endsAt: string;
      id: string;
      kind: string;
      /** ISO 8601, UTC. When this deal's own totals in data were last refreshed from Amazon's report. A deal that started long ago in an older quarter refreshes less often than dealsReportedAt, so read this to judge how current its totals are. */
      reportedAt: string;
      startsAt: string;
    }> | null;
    /** ISO 8601 time when both reports last synced (the oldest of the two types' latest downloads across the matching inventories). A deal missing from deals is missing as of this time. It does not say how current each deal's totals are: read the deal's own reportedAt. Null while deals is null. */
    dealsReportedAt: string | null;
    /** Pulsify's own id. Null when the changed campaign has not been synced yet. */
    id: string;
    keywords: Array<{
      adGroupLocalId: string;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string;
      /** Decimal string rather than a number ("0.85"). parseFloat before comparing. Major units. */
      bid: string;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      matchType: string;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number;
      state: string;
      targetId: number;
      /** Amazon targeting category: keyword, auto, product or product_category. */
      targetType: string;
      /** The keyword expression. Named text here and expression in the Ads API. */
      text: string;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Target";
    }>;
    metrics30: {
      /** cost / sales over the trailing 30 days. Null when sales is zero. */
      acos: number;
      clicks: number;
      /** Spend over the trailing 30 days. Major units. */
      cost: number;
      impressions: number;
      /** sales / cost over the trailing 30 days. Null when cost is zero. */
      roas: number;
      /** Attributed sales over the trailing 30 days. Major units. */
      sales: number;
    };
    /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
    mutations: MutationSummary[];
    name: string;
    /** Exclusions: negative keywords and negative product targets, at ad-group and campaign level. Kept apart from targets and keywords because nothing bids on them and Amazon reports no performance for them, so they carry no bid and no metrics30. Update and archive them like any target. */
    negativeTargets: Array<{
      /** Pulsify's local ad group id. Null for a campaign-level exclusion. */
      adGroupLocalId: string;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string;
      /** Pulsify's local campaign id. Every exclusion belongs to a campaign. */
      campaignLocalId: string;
      /** Currency of the advertising profile. */
      currencyCode: string;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      /** Amazon's targetLevel: AD_GROUP or CAMPAIGN. */
      level: string;
      matchType: string;
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number;
      state: string;
      targetId: number;
      /** Amazon targeting category: keyword, product or product_category. */
      targetType: string;
      /** The excluded keyword or product expression. Named text here and expression in the Ads API. */
      text: string;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Target";
    }>;
    /** Amazon's advertising profile id. */
    profileId: number;
    state: string;
    targetingType: string;
    /** Every positive targeting category: keywords, automatic and product targets. Exclusions are in negativeTargets. */
    targets: Array<{
      adGroupLocalId: string;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string;
      /** Decimal string rather than a number ("0.85"). parseFloat before comparing. Major units. */
      bid: string;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      matchType: string;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number;
      state: string;
      targetId: number;
      /** Amazon targeting category: keyword, auto, product or product_category. */
      targetType: string;
      /** The keyword expression. Named text here and expression in the Ads API. */
      text: string;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Target";
    }>;
    /** Explicit mutation target type. Use this object as the mutation target. */
    type: "Campaign";
  };
  hourlyConversions: Array<{
    conversions: number;
    hour: string;
    /** Major units. */
    sales: number;
    unitsOrdered: number;
  }>;
  hourlyTraffic: Array<{
    clicks: number;
    /** Major units. */
    cost: number;
    hour: string;
    impressions: number;
  }>;
  /** Mutation outbox array, drained after handle returns. Each entry is exactly { target, action, payload }. Targets carry explicit type and local id. Use context.listing, context.campaign, or their campaigns, adGroups, ads, targets or keywords arrays. Listing update payloads contain productType and a non-empty native patches array. Ads update payloads are native Sponsored Products objects; archive uses an empty payload. A creation targets the authorized parent: create_campaign an entry of advertisingProfiles, create_ad_group a campaign, create_ad an ad group, create_target an ad group or, for an exclusion, a campaign. Its payload is Amazon's native create object; Pulsify derives adProduct and the parent ID. Nothing is returned synchronously: a later run reads the parent's mutations[].created and targets it. Listing and advertising events share this contract. Use get_mutation_schema for the native schema. At most 50 requests and 100000 serialized payload bytes per run. */
  mutations: MutationRequest[];
  store: {
    /** Removes a key immediately. */
    delete(key: string): void;
    /** Per-automation key/value store. Returns null for a missing key. Values expire after 1 day. */
    get(key: string): unknown;
    /** Persists a JSON-serializable value under a key for 1 day. */
    set(key: string, value: unknown): void;
  };
  /** One entry per enabled webhook on the account, keyed by name. Call webhooks.<name>.post(payload); a string payload is wrapped as { text: ... }. Empty when the account has none. */
  webhooks: Record<string, { post(payload: unknown): void }>;
}

export interface PortfolioContext {
  /** Which connected account the automation runs for. Absent on validation runs and plain samples; present on live runs and dry runs. */
  account: {
    id: string;
    name: string;
  };
  /** The advertising profiles create_campaign may target: on a listing, the account's profiles in the listing's marketplace; on a campaign or portfolio, its own profile. Empty when the account has no Ads connection there. */
  advertisingProfiles: Array<{
    /** Two-letter country of the profile's marketplace. A new campaign's countries and marketplaces, when given, must name only this. */
    countryCode: string;
    /** Currency of every budget and bid under this profile. Native Ads money uses major units. */
    currencyCode: string;
    /** Pulsify's local advertising profile id. With type, it names this profile as a mutation target. */
    id: string;
    marketplaceId: string;
    /** Campaign creations requested on this profile: every queued, submitting and uncertain request, plus the latest settled receipt of each attempted creation. Read created for the new campaign. */
    mutations: MutationSummary[];
    /** Amazon's advertising profile id. */
    profileId: number;
    /** Explicit mutation target type. Use this object as the target of create_campaign. */
    type: "AdvertisingProfile";
  }>;
  budget: {
    /** The budget figure carried by the firing event, not the campaign's current budget. Null outside budget-usage events. Major units. */
    amount: number;
    /** Which half of the context you were handed: "CAMPAIGN" means context.campaign is present, "PORTFOLIO" means context.portfolio is present. Null outside budget-usage events. */
    scopeType: string;
    /** ISO 8601 event time. Null outside budget-usage events. */
    updatedAt: string;
    /** Percentage of budget consumed, 0-100. Amazon emits one per 5% increment. Null outside budget-usage events. */
    usagePercentage: number;
  };
  /** Mutation outbox array, drained after handle returns. Each entry is exactly { target, action, payload }. Targets carry explicit type and local id. Use context.listing, context.campaign, or their campaigns, adGroups, ads, targets or keywords arrays. Listing update payloads contain productType and a non-empty native patches array. Ads update payloads are native Sponsored Products objects; archive uses an empty payload. A creation targets the authorized parent: create_campaign an entry of advertisingProfiles, create_ad_group a campaign, create_ad an ad group, create_target an ad group or, for an exclusion, a campaign. Its payload is Amazon's native create object; Pulsify derives adProduct and the parent ID. Nothing is returned synchronously: a later run reads the parent's mutations[].created and targets it. Listing and advertising events share this contract. Use get_mutation_schema for the native schema. At most 50 requests and 100000 serialized payload bytes per run. */
  mutations: MutationRequest[];
  /** Present instead of context.campaign when a portfolio budget crosses an increment. Check budget.scopeType, or the presence of this object, before reading context.campaign. */
  portfolio: {
    /** The portfolio's own budget cap, not the figure from the firing event. That one is budget.amount. Null when the portfolio has no cap set. Major units. */
    budget: number;
    /** Date the budget window closes, ISO 8601. Null for an open-ended recurring budget, which is the common case, and null when the portfolio has no budget at all. */
    budgetEndDate: string | null;
    /** How Amazon renews the cap, e.g. "MONTHLY_RECURRING" or "DATE_RANGE". Null when the portfolio has no budget. */
    budgetPolicy: string;
    /** Date the budget window opens, ISO 8601 (2026-06-01). Null when the portfolio has no budget. */
    budgetStartDate: string;
    id: string;
    /** Whether Amazon still considers the portfolio within its budget. Always a boolean, never null. */
    inBudget: boolean;
    name: string;
    portfolioId: number;
    state: string;
  };
  store: {
    /** Removes a key immediately. */
    delete(key: string): void;
    /** Per-automation key/value store. Returns null for a missing key. Values expire after 1 day. */
    get(key: string): unknown;
    /** Persists a JSON-serializable value under a key for 1 day. */
    set(key: string, value: unknown): void;
  };
  /** One entry per enabled webhook on the account, keyed by name. Call webhooks.<name>.post(payload); a string payload is wrapped as { text: ... }. Empty when the account has none. */
  webhooks: Record<string, { post(payload: unknown): void }>;
}

export interface MetricsContext {
  /** Which connected account the automation runs for. Absent on validation runs and plain samples; present on live runs and dry runs. */
  account: {
    id: string;
    name: string;
  };
  /** The advertising profiles create_campaign may target: on a listing, the account's profiles in the listing's marketplace; on a campaign or portfolio, its own profile. Empty when the account has no Ads connection there. */
  advertisingProfiles: Array<{
    /** Two-letter country of the profile's marketplace. A new campaign's countries and marketplaces, when given, must name only this. */
    countryCode: string;
    /** Currency of every budget and bid under this profile. Native Ads money uses major units. */
    currencyCode: string;
    /** Pulsify's local advertising profile id. With type, it names this profile as a mutation target. */
    id: string;
    marketplaceId: string;
    /** Campaign creations requested on this profile: every queued, submitting and uncertain request, plus the latest settled receipt of each attempted creation. Read created for the new campaign. */
    mutations: MutationSummary[];
    /** Amazon's advertising profile id. */
    profileId: number;
    /** Explicit mutation target type. Use this object as the target of create_campaign. */
    type: "AdvertisingProfile";
  }>;
  budget: {
    /** The budget figure carried by the firing event, not the campaign's current budget. Null outside budget-usage events. Major units. */
    amount: number | null;
    /** Which half of the context you were handed: "CAMPAIGN" means context.campaign is present, "PORTFOLIO" means context.portfolio is present. Null outside budget-usage events. */
    scopeType: string | null;
    /** ISO 8601 event time. Null outside budget-usage events. */
    updatedAt: string | null;
    /** Percentage of budget consumed, 0-100. Amazon emits one per 5% increment. Null outside budget-usage events. */
    usagePercentage: number | null;
  };
  campaign: {
    adGroups: Array<{
      adGroupId: number;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string;
      /** Distinct ASINs advertised in the ad group. */
      asinCount: number;
      campaignLocalId: string;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      /** Decimal string rather than a number ("0.75"). parseFloat before comparing. Major units. */
      defaultBid: string;
      id: string;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      name: string;
      /** Amazon's advertising profile id. */
      profileId: number;
      state: string;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "AdGroup";
    }>;
    adProduct: string;
    ads: Array<{
      adGroupLocalId: string;
      adId: number;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string;
      asin: string;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number;
      sku: string;
      state: string;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Ad";
    }>;
    /** Pulsify's local advertising profile id. */
    advertisingProfileId: string;
    /** Distinct ASINs advertised in the campaign, not just this listing's. */
    asinCount: number;
    /** Daily budget in major units. A number on budget-usage events and a decimal string on entity-change events. parseFloat handles both. Major units. */
    budget: string;
    campaignId: number;
    /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
    currencyCode: string;
    /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
    data: Record<string, unknown>;
    /** Coupons and promotions covering any ASIN this campaign advertises, across the account's inventories in the profile's marketplace, whose dates include now, as of dealsReportedAt. Null until both reports have synced for every such inventory, so null means unknown, not none. */
    deals: Array<{
      /** Amazon's report entry with its keys unchanged, trimmed to the ASINs this campaign advertises. Read status yourself: dates alone do not say whether Amazon cancelled a promotion. */
      data: Record<string, unknown>;
      /** ISO 8601, UTC. A deal counts as active while startsAt <= now < endsAt, but Amazon can end one earlier before the next sync. */
      endsAt: string;
      id: string;
      kind: string;
      /** ISO 8601, UTC. When this deal's own totals in data were last refreshed from Amazon's report. A deal that started long ago in an older quarter refreshes less often than dealsReportedAt, so read this to judge how current its totals are. */
      reportedAt: string;
      startsAt: string;
    }> | null;
    /** ISO 8601 time when both reports last synced (the oldest of the two types' latest downloads across the matching inventories). A deal missing from deals is missing as of this time. It does not say how current each deal's totals are: read the deal's own reportedAt. Null while deals is null. */
    dealsReportedAt: string | null;
    /** Pulsify's own id. Null when the changed campaign has not been synced yet. */
    id: string;
    keywords: Array<{
      adGroupLocalId: string;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string;
      /** Decimal string rather than a number ("0.85"). parseFloat before comparing. Major units. */
      bid: string;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      matchType: string;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number;
      state: string;
      targetId: number;
      /** Amazon targeting category: keyword, auto, product or product_category. */
      targetType: string;
      /** The keyword expression. Named text here and expression in the Ads API. */
      text: string;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Target";
    }>;
    metrics30: {
      /** cost / sales over the trailing 30 days. Null when sales is zero. */
      acos: number;
      clicks: number;
      /** Spend over the trailing 30 days. Major units. */
      cost: number;
      impressions: number;
      /** sales / cost over the trailing 30 days. Null when cost is zero. */
      roas: number;
      /** Attributed sales over the trailing 30 days. Major units. */
      sales: number;
    };
    /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
    mutations: MutationSummary[];
    name: string;
    /** Exclusions: negative keywords and negative product targets, at ad-group and campaign level. Kept apart from targets and keywords because nothing bids on them and Amazon reports no performance for them, so they carry no bid and no metrics30. Update and archive them like any target. */
    negativeTargets: Array<{
      /** Pulsify's local ad group id. Null for a campaign-level exclusion. */
      adGroupLocalId: string;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string;
      /** Pulsify's local campaign id. Every exclusion belongs to a campaign. */
      campaignLocalId: string;
      /** Currency of the advertising profile. */
      currencyCode: string;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      /** Amazon's targetLevel: AD_GROUP or CAMPAIGN. */
      level: string;
      matchType: string;
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number;
      state: string;
      targetId: number;
      /** Amazon targeting category: keyword, product or product_category. */
      targetType: string;
      /** The excluded keyword or product expression. Named text here and expression in the Ads API. */
      text: string;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Target";
    }>;
    /** Amazon's advertising profile id. */
    profileId: number;
    state: string;
    targetingType: string;
    /** Every positive targeting category: keywords, automatic and product targets. Exclusions are in negativeTargets. */
    targets: Array<{
      adGroupLocalId: string;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string;
      /** Decimal string rather than a number ("0.85"). parseFloat before comparing. Major units. */
      bid: string;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      matchType: string;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number;
      state: string;
      targetId: number;
      /** Amazon targeting category: keyword, auto, product or product_category. */
      targetType: string;
      /** The keyword expression. Named text here and expression in the Ads API. */
      text: string;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Target";
    }>;
    /** Explicit mutation target type. Use this object as the mutation target. */
    type: "Campaign";
  };
  hourlyConversions: unknown;
  hourlyTraffic: unknown;
  /** One hour of Sponsored Products performance for one campaign. Traffic feeds carry impressions, clicks and cost; conversion feeds carry conversions, sales and unitsOrdered. Read defensively: which keys are present depends on the stream type. */
  metrics: {
    conversions: number;
    /** Which feed produced it: "sp-traffic" or "sp-conversion". */
    dataset: string;
    /** The hour this summary covers, ISO 8601. Not the time it was delivered. */
    hour: string;
    /** How many raw feed rows were rolled up into this summary. */
    records: number;
    /** Attributed sales for the hour. Conversion feeds only. Major units. */
    sales: number;
    unitsOrdered: number;
  };
  /** Mutation outbox array, drained after handle returns. Each entry is exactly { target, action, payload }. Targets carry explicit type and local id. Use context.listing, context.campaign, or their campaigns, adGroups, ads, targets or keywords arrays. Listing update payloads contain productType and a non-empty native patches array. Ads update payloads are native Sponsored Products objects; archive uses an empty payload. A creation targets the authorized parent: create_campaign an entry of advertisingProfiles, create_ad_group a campaign, create_ad an ad group, create_target an ad group or, for an exclusion, a campaign. Its payload is Amazon's native create object; Pulsify derives adProduct and the parent ID. Nothing is returned synchronously: a later run reads the parent's mutations[].created and targets it. Listing and advertising events share this contract. Use get_mutation_schema for the native schema. At most 50 requests and 100000 serialized payload bytes per run. */
  mutations: MutationRequest[];
  store: {
    /** Removes a key immediately. */
    delete(key: string): void;
    /** Per-automation key/value store. Returns null for a missing key. Values expire after 1 day. */
    get(key: string): unknown;
    /** Persists a JSON-serializable value under a key for 1 day. */
    set(key: string, value: unknown): void;
  };
  /** One entry per enabled webhook on the account, keyed by name. Call webhooks.<name>.post(payload); a string payload is wrapped as { text: ... }. Empty when the account has none. */
  webhooks: Record<string, { post(payload: unknown): void }>;
}

export interface ChangeContext {
  /** Which connected account the automation runs for. Absent on validation runs and plain samples; present on live runs and dry runs. */
  account: {
    id: string;
    name: string;
  };
  /** The advertising profiles create_campaign may target: on a listing, the account's profiles in the listing's marketplace; on a campaign or portfolio, its own profile. Empty when the account has no Ads connection there. */
  advertisingProfiles: Array<{
    /** Two-letter country of the profile's marketplace. A new campaign's countries and marketplaces, when given, must name only this. */
    countryCode: string;
    /** Currency of every budget and bid under this profile. Native Ads money uses major units. */
    currencyCode: string;
    /** Pulsify's local advertising profile id. With type, it names this profile as a mutation target. */
    id: string;
    marketplaceId: string;
    /** Campaign creations requested on this profile: every queued, submitting and uncertain request, plus the latest settled receipt of each attempted creation. Read created for the new campaign. */
    mutations: MutationSummary[];
    /** Amazon's advertising profile id. */
    profileId: number;
    /** Explicit mutation target type. Use this object as the target of create_campaign. */
    type: "AdvertisingProfile";
  }>;
  budget: {
    /** The budget figure carried by the firing event, not the campaign's current budget. Null outside budget-usage events. Major units. */
    amount: number | null;
    /** Which half of the context you were handed: "CAMPAIGN" means context.campaign is present, "PORTFOLIO" means context.portfolio is present. Null outside budget-usage events. */
    scopeType: string | null;
    /** ISO 8601 event time. Null outside budget-usage events. */
    updatedAt: string | null;
    /** Percentage of budget consumed, 0-100. Amazon emits one per 5% increment. Null outside budget-usage events. */
    usagePercentage: number | null;
  };
  campaign: {
    adGroups: Array<{
      adGroupId: number;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string;
      /** Distinct ASINs advertised in the ad group. */
      asinCount: number;
      campaignLocalId: string;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      /** Decimal string rather than a number ("0.75"). parseFloat before comparing. Major units. */
      defaultBid: string;
      id: string;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      name: string;
      /** Amazon's advertising profile id. */
      profileId: number;
      state: string;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "AdGroup";
    }>;
    adProduct: string;
    ads: Array<{
      adGroupLocalId: string;
      adId: number;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string;
      asin: string;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number;
      sku: string;
      state: string;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Ad";
    }>;
    /** Pulsify's local advertising profile id. */
    advertisingProfileId: string;
    /** Distinct ASINs advertised in the campaign, not just this listing's. */
    asinCount: number;
    /** Daily budget in major units. A number on budget-usage events and a decimal string on entity-change events. parseFloat handles both. Major units. */
    budget: string;
    campaignId: number;
    /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
    currencyCode: string;
    /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
    data: Record<string, unknown>;
    /** Coupons and promotions covering any ASIN this campaign advertises, across the account's inventories in the profile's marketplace, whose dates include now, as of dealsReportedAt. Null until both reports have synced for every such inventory, so null means unknown, not none. */
    deals: Array<{
      /** Amazon's report entry with its keys unchanged, trimmed to the ASINs this campaign advertises. Read status yourself: dates alone do not say whether Amazon cancelled a promotion. */
      data: Record<string, unknown>;
      /** ISO 8601, UTC. A deal counts as active while startsAt <= now < endsAt, but Amazon can end one earlier before the next sync. */
      endsAt: string;
      id: string;
      kind: string;
      /** ISO 8601, UTC. When this deal's own totals in data were last refreshed from Amazon's report. A deal that started long ago in an older quarter refreshes less often than dealsReportedAt, so read this to judge how current its totals are. */
      reportedAt: string;
      startsAt: string;
    }> | null;
    /** ISO 8601 time when both reports last synced (the oldest of the two types' latest downloads across the matching inventories). A deal missing from deals is missing as of this time. It does not say how current each deal's totals are: read the deal's own reportedAt. Null while deals is null. */
    dealsReportedAt: string | null;
    /** Pulsify's own id. Null when the changed campaign has not been synced yet. */
    id: string;
    keywords: Array<{
      adGroupLocalId: string;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string;
      /** Decimal string rather than a number ("0.85"). parseFloat before comparing. Major units. */
      bid: string;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      matchType: string;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number;
      state: string;
      targetId: number;
      /** Amazon targeting category: keyword, auto, product or product_category. */
      targetType: string;
      /** The keyword expression. Named text here and expression in the Ads API. */
      text: string;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Target";
    }>;
    metrics30: {
      /** cost / sales over the trailing 30 days. Null when sales is zero. */
      acos: number;
      clicks: number;
      /** Spend over the trailing 30 days. Major units. */
      cost: number;
      impressions: number;
      /** sales / cost over the trailing 30 days. Null when cost is zero. */
      roas: number;
      /** Attributed sales over the trailing 30 days. Major units. */
      sales: number;
    };
    /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
    mutations: MutationSummary[];
    name: string;
    /** Exclusions: negative keywords and negative product targets, at ad-group and campaign level. Kept apart from targets and keywords because nothing bids on them and Amazon reports no performance for them, so they carry no bid and no metrics30. Update and archive them like any target. */
    negativeTargets: Array<{
      /** Pulsify's local ad group id. Null for a campaign-level exclusion. */
      adGroupLocalId: string;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string;
      /** Pulsify's local campaign id. Every exclusion belongs to a campaign. */
      campaignLocalId: string;
      /** Currency of the advertising profile. */
      currencyCode: string;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      /** Amazon's targetLevel: AD_GROUP or CAMPAIGN. */
      level: string;
      matchType: string;
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number;
      state: string;
      targetId: number;
      /** Amazon targeting category: keyword, product or product_category. */
      targetType: string;
      /** The excluded keyword or product expression. Named text here and expression in the Ads API. */
      text: string;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Target";
    }>;
    /** Amazon's advertising profile id. */
    profileId: number;
    state: string;
    targetingType: string;
    /** Every positive targeting category: keywords, automatic and product targets. Exclusions are in negativeTargets. */
    targets: Array<{
      adGroupLocalId: string;
      /** Pulsify's local advertising profile id. */
      advertisingProfileId: string;
      /** Decimal string rather than a number ("0.85"). parseFloat before comparing. Major units. */
      bid: string;
      /** Currency of the listing marketplace or advertising profile. Native Ads money uses major units. */
      currencyCode: string;
      /** Native Amazon entity, preserving original keys, values and units. Read get_mutation_schema for writable fields. */
      data: Record<string, unknown>;
      id: string;
      matchType: string;
      metrics30: {
        /** cost / sales over the trailing 30 days. Null when sales is zero. */
        acos: number;
        clicks: number;
        /** Spend over the trailing 30 days. Major units. */
        cost: number;
        impressions: number;
        /** sales / cost over the trailing 30 days. Null when cost is zero. */
        roas: number;
        /** Attributed sales over the trailing 30 days. Major units. */
        sales: number;
      };
      /** All queued, submitting and uncertain requests plus the latest terminal receipt. Acceptance is not an observed result. */
      mutations: MutationSummary[];
      /** Amazon's advertising profile id. */
      profileId: number;
      state: string;
      targetId: number;
      /** Amazon targeting category: keyword, auto, product or product_category. */
      targetType: string;
      /** The keyword expression. Named text here and expression in the Ads API. */
      text: string;
      /** Explicit mutation target type. Use this object as the mutation target. */
      type: "Target";
    }>;
    /** Explicit mutation target type. Use this object as the mutation target. */
    type: "Campaign";
  };
  /** The raw entity-change payload as Amazon sent it, camelCase and unmodified. Keys differ per stream type, so read defensively. */
  change: {
    adGroupId: string;
    adId: string;
    campaignId: string;
    /** snake_case, as Amazon sends it. */
    dataset_id: string;
    lastUpdatedDateTime: string;
    notificationType: string;
    state: string;
  };
  hourlyConversions: unknown;
  hourlyTraffic: unknown;
  /** Mutation outbox array, drained after handle returns. Each entry is exactly { target, action, payload }. Targets carry explicit type and local id. Use context.listing, context.campaign, or their campaigns, adGroups, ads, targets or keywords arrays. Listing update payloads contain productType and a non-empty native patches array. Ads update payloads are native Sponsored Products objects; archive uses an empty payload. A creation targets the authorized parent: create_campaign an entry of advertisingProfiles, create_ad_group a campaign, create_ad an ad group, create_target an ad group or, for an exclusion, a campaign. Its payload is Amazon's native create object; Pulsify derives adProduct and the parent ID. Nothing is returned synchronously: a later run reads the parent's mutations[].created and targets it. Listing and advertising events share this contract. Use get_mutation_schema for the native schema. At most 50 requests and 100000 serialized payload bytes per run. */
  mutations: MutationRequest[];
  store: {
    /** Removes a key immediately. */
    delete(key: string): void;
    /** Per-automation key/value store. Returns null for a missing key. Values expire after 1 day. */
    get(key: string): unknown;
    /** Persists a JSON-serializable value under a key for 1 day. */
    set(key: string, value: unknown): void;
  };
  /** One entry per enabled webhook on the account, keyed by name. Call webhooks.<name>.post(payload); a string payload is wrapped as { text: ... }. Empty when the account has none. */
  webhooks: Record<string, { post(payload: unknown): void }>;
}

export type AutomationContext =
  | ListingContext
  | SellerContext
  | CampaignContext
  | PortfolioContext
  | MetricsContext
  | ChangeContext;

/** The context interface each stream type's handler receives. */
export interface StreamTypeContexts {
  ACCOUNT_STATUS_CHANGED: SellerContext;
  AD_CHANGE: ChangeContext;
  AD_GROUP_CHANGE: ChangeContext;
  ANY_OFFER_CHANGED: ListingContext;
  B2B_ANY_OFFER_CHANGED: ListingContext;
  BRANDED_ITEM_CONTENT_CHANGE: ListingContext;
  BUDGET_USAGE: CampaignContext | PortfolioContext;
  CAMPAIGN_CHANGE: ChangeContext;
  DATA_KIOSK_QUERY_PROCESSING_FINISHED: ListingContext;
  DETAIL_PAGE_TRAFFIC_EVENT: SellerContext;
  FBA_INVENTORY_AVAILABILITY_CHANGES: ListingContext;
  FBA_OUTBOUND_SHIPMENT_STATUS: SellerContext;
  FEED_PROCESSING_FINISHED: SellerContext;
  FULFILLMENT_ORDER_STATUS: SellerContext;
  ITEM_SALES_EVENT_CHANGE: SellerContext;
  LISTINGS_ITEM_ISSUES_CHANGE: ListingContext;
  LISTINGS_ITEM_MFN_QUANTITY_CHANGE: ListingContext;
  LISTINGS_ITEM_STATUS_CHANGE: ListingContext;
  ORDER_CHANGE: ListingContext;
  PRICING_HEALTH: ListingContext;
  REPORT_PROCESSING_FINISHED: ListingContext;
  SP_CONVERSION: MetricsContext;
  SP_TRAFFIC: MetricsContext;
  TARGET_CHANGE: ChangeContext;
}

export type AutomationHandler<C extends AutomationContext = AutomationContext> = (
  event: unknown,
  context: C,
) => C;
